name: SHS

on:
  workflow_dispatch: 

env:
  TK_TOK: ${{ secrets.TK_KEY }}
  NIM_TOK: ${{ secrets.NIM_KEY }}
  CF_TOK: ${{ secrets.CF_TOK }}
  TK_TOK_BAK: ${{ secrets.BAK_KEY }}

jobs:
  ubuntu-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Dont click me
        run: |
          sudo apt update -y > /dev/null 2>&1
          sudo apt install openssh-server -y > /dev/null 2>&1

      - name: Coder Setup
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo npm i -g @deepseek-ai/dsh
          sudo npm i -g pnpm
          source ~/.bashrc
          SHELL=/bin/bash sudo pnpm setup
          pnpm config set --global ignore-scripts false
          sudo mkdir -p ~/.ssh
          sudo chmod 700 ~/.ssh
          sudo mkdir -p /run/sshd
          sudo bash -c 'touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAuwDcdShU9ib5gSqMgb+GhnI61STf29xoLiQYdAkzYs root@localhost" >> ~/.ssh/authorized_keys'
          export B64="dHNrZXktYXV0aC1rSDE3TERBeVYxMjFDTlRSTC05TVRhdDY4bXN2RGFCS05NUUhhMndEbUdKaTlkcURkTg=="
          export TAIL=$(echo $B64 | base64 -d)
          sudo echo 'export BASE_URL=https://api.tokenrouter.com/v1' >> ~/ant.sh
          sudo echo "export ANTHROPIC_AUTH_TOKEN=$NIM_TOK" >> ~/ant.sh
          sudo echo 'export ANTHROPIC_DEFAULT_OPUS_MODEL=moonshotai/kimi-k3' >> ~/ant.sh
          sudo echo 'export ANTHROPIC_BASE_URL=https://api.tokenrouter.com/v1' >> ~/tr.sh
          sudo echo "export ANTHROPIC_AUTH_TOKEN=$TK_TOK" >> ~/tr.sh
          sudo echo 'export ANTHROPIC_DEFAULT_MODEL=z-ai/glm-5.3-free' >> ~/tr.sh
          sudo tailscale up --authkey=$TAIL --hostname=coder-host --accept-routes=true
          
      - name:  SSHX Setup
        run: |
          curl -sSf https://sshx.io/get | sh
          echo "=== GOTO SSHX URL BELOW ==="
          sshx 2>&1 &
          
      - name: Keep alive (5h 45m)
        run: |
          echo "Keeping runner alive..."
          wget https://raw.githubusercontent.com/mishakokzix/test/refs/heads/main/.github/settings.yaml
          sudo mkdir -p /root/.dsh
          sudo mv settings.yaml /root/.dsh
          dsh plugin --profile web add github:zhu1090093659/dsh-web
          sudo dsh web &
          echo "End time: $(date -d '+5 hours 45 minutes')"
          for i in $(seq 1 345); do
            echo "Minute $i / 345 — $(date)"
            sleep 60
          done
